# Generated by Django 4.0.2 on 2022-02-23 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_region_site_email_site_owner_site_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safeambassador',
            name='email',
        ),
        migrations.AddField(
            model_name='region',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
