# Generated by Django 4.0.2 on 2022-02-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='anonymous_id',
        ),
    ]
