# Generated by Django 2.1 on 2022-02-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0006_auto_20220226_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('should_ban', models.BooleanField()),
            ],
        ),
    ]
