# Generated by Django 2.1 on 2022-02-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0007_coffee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
